name: 自动同步pixiv上的画师文件

on:
  schedule:
    - cron: '0 23/11 * * *'
#  workflow_dispatch:
#   USERNAME:
#      type: string
#      default: ''
#      description: 'test'
#      required: false

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      #email
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Git PixivCrawler
        run: |
          git clone https://github.com/plana-planetarium/PixivCrawler.git

      - name: Install Dependency
        run: |
          python -m pip install --upgrade pip
          pip install -r ./PixivCrawler/requirements.txt

      - name: Downloading
        continue-on-error: false
        run: |
          python main.py


      - name: Upload File A.R.O.N.A
        uses: actions/upload-artifact@v3
        with:
          name: A.R.O.N.A
          path: ./Downloads/A.R.O.N.A/
          if-no-files-found: ignore
          retention-days: 7
      - name: Send Email A.R.O.N.A
        run: |
          export NAME_USER="A.R.O.N.A"
          python upload_email.py


      - name: Upload File EnMa0
        uses: actions/upload-artifact@v3
        with:
          name: EnMa0
          path: ./Downloads/EnMa0/
          if-no-files-found: ignore
          retention-days: 7
      - name: Send Email EnMa0
        run: |
          export NAME_USER="EnMa0"
          python upload_email.py

      - name: Git push log
        run: |
          rm -rf ./PixivCrawler
          rm -rf ./Downloads
          git config --global user.name "plana-planetarium"
          git config --global user.email "3412294524@qq.com"
          git init
          git remote remove origin
          git remote add origin git@github.com:plana-planetarium/pixiv_sync.git
          git add ./downloads_log
          git commit -m "Update downloads logs"

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
